## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.callbacks import Callback, ModelCheckpoint

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = counts[counts < 528].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classifications = application_df['CLASSIFICATION'].value_counts()
classifications

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1248        1
C6100        1
C1820        1
C1900        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_mod = classifications.loc[classifications > 1]
classifications_mod

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C2400        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1256        2
C1246        2
C1234        2
C1267        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classifications[classifications < 1883].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df, dtype=int)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
X = application_dummies.drop(['IS_SUCCESSFUL'], axis=1)
y = application_dummies['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train_scaled.shape[1]
hn_layer1 = number_input_features * 2
hn_layer2 = hn_layer1 // 2

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Input(shape=(number_input_features,)))
nn.add(tf.keras.layers.Dense(units=hn_layer1, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hn_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 86)                  │           3,784 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 43)                  │           3,741 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              44 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,569 (29.57 KB)

 Trainable params: 7,569 (29.57 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Callback
class SaveEpochs(Callback):
    def __init__(self, filepath, save_freq=5):
        super(SaveEpochs, self).__init__()
        self.filepath = filepath
        self.save_freq = save_freq

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.save_freq == 0:
            self.model.save_weights(self.filepath)
            print(f"\n🔹 Model weights saved at epoch {epoch + 1}")

# Set callback to save every 5 epochs
checkpoint_cb = SaveEpochs(filepath="AlphabetSoupCharity.weights.h5", save_freq=5)

In [ ]:
# Train the model
trained_model = nn.fit(X_train_scaled, y_train, epochs=100, validation_data=(X_test_scaled, y_test), callbacks=[checkpoint_cb])

Epoch 1/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.7085 - loss: 0.5827 - val_accuracy: 0.7197 - val_loss: 0.5630
Epoch 2/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7283 - loss: 0.5553 - val_accuracy: 0.7235 - val_loss: 0.5616
Epoch 3/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7254 - loss: 0.5580 - val_accuracy: 0.7254 - val_loss: 0.5617
Epoch 4/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7286 - loss: 0.5544 - val_accuracy: 0.7222 - val_loss: 0.5617
Epoch 5/100
837/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7277 - loss: 0.5528
🔹 Model weights saved at epoch 5
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7278 - loss: 0.5527 - val_accuracy: 0.7281 - val_loss: 0.5579
Epoch 6/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7360 - loss: 0.5432 - val_accuracy: 0.7208 - val_loss: 0.5591
Epoch 7/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7346 - loss: 0.5482 - val_accuracy: 0.7277 - val_loss: 0.5596
Epoch 8/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7348 - loss: 0.5408 - val_accuracy: 0.7236 - val_loss: 0.5576
Epoch 9/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7380 - loss: 0.5402 - val_accuracy: 0.7283 - val_loss: 0.5556
Epoch 10/100
848/858 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7364 - loss: 0.5426
🔹 Model weights saved at epoch 10
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7364 - loss: 0.5427 - val_accuracy: 0.7238 - val_loss: 0.5583
Epoch 11/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7370 - loss: 0.5419 - val_accuracy: 0.7283 - val_loss: 0.5581
Epoch 12/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7325 - loss: 0.5448 - val_accuracy: 0.7293 - val_loss: 0.5575
Epoch 13/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7370 - loss: 0.5440 - val_accuracy: 0.7255 - val_loss: 0.5567
Epoch 14/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7362 - loss: 0.5414 - val_accuracy: 0.7270 - val_loss: 0.5574
Epoch 15/100
852/858 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7356 - loss: 0.5405
🔹 Model weights saved at epoch 15
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7356 - loss: 0.5406 - val_accuracy: 0.7268 - val_loss: 0.5593
Epoch 16/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7353 - loss: 0.5408 - val_accuracy: 0.7259 - val_loss: 0.5591
Epoch 17/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7400 - loss: 0.5361 - val_accuracy: 0.7289 - val_loss: 0.5573
Epoch 18/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7353 - loss: 0.5447 - val_accuracy: 0.7222 - val_loss: 0.5597
Epoch 19/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7375 - loss: 0.5404 - val_accuracy: 0.7255 - val_loss: 0.5599
Epoch 20/100
853/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7367 - loss: 0.5417
🔹 Model weights saved at epoch 20
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7367 - loss: 0.5417 - val_accuracy: 0.7261 - val_loss: 0.5584
Epoch 21/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7350 - loss: 0.5384 - val_accuracy: 0.7286 - val_loss: 0.5598
Epoch 22/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7331 - loss: 0.5460 - val_accuracy: 0.7262 - val_loss: 0.5595
Epoch 23/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7409 - loss: 0.5364 - val_accuracy: 0.7261 - val_loss: 0.5588
Epoch 24/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7392 - loss: 0.5394 - val_accuracy: 0.7281 - val_loss: 0.5576
Epoch 25/100
852/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7343 - loss: 0.5384
🔹 Model weights saved at epoch 25
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7343 - loss: 0.5384 - val_accuracy: 0.7261 - val_loss: 0.5597
Epoch 26/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7380 - loss: 0.5388 - val_accuracy: 0.7262 - val_loss: 0.5602
Epoch 27/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7422 - loss: 0.5352 - val_accuracy: 0.7254 - val_loss: 0.5578
Epoch 28/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7410 - loss: 0.5386 - val_accuracy: 0.7281 - val_loss: 0.5581
Epoch 29/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7385 - loss: 0.5409 - val_accuracy: 0.7270 - val_loss: 0.5594
Epoch 30/100
851/858 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7385 - loss: 0.5385
🔹 Model weights saved at epoch 30
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7385 - loss: 0.5385 - val_accuracy: 0.7259 - val_loss: 0.5591
Epoch 31/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7376 - loss: 0.5397 - val_accuracy: 0.7274 - val_loss: 0.5575
Epoch 32/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7430 - loss: 0.5352 - val_accuracy: 0.7259 - val_loss: 0.5601
Epoch 33/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7402 - loss: 0.5349 - val_accuracy: 0.7248 - val_loss: 0.5602
Epoch 34/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7377 - loss: 0.5361 - val_accuracy: 0.7261 - val_loss: 0.5600
Epoch 35/100
847/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7389 - loss: 0.5363
🔹 Model weights saved at epoch 35
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7389 - loss: 0.5364 - val_accuracy: 0.7262 - val_loss: 0.5580
Epoch 36/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7384 - loss: 0.5356 - val_accuracy: 0.7290 - val_loss: 0.5596
Epoch 37/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7427 - loss: 0.5328 - val_accuracy: 0.7264 - val_loss: 0.5605
Epoch 38/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7336 - loss: 0.5397 - val_accuracy: 0.7264 - val_loss: 0.5590
Epoch 39/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7385 - loss: 0.5358 - val_accuracy: 0.7259 - val_loss: 0.5603
Epoch 40/100
854/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7387 - loss: 0.5374
🔹 Model weights saved at epoch 40
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7387 - loss: 0.5374 - val_accuracy: 0.7255 - val_loss: 0.5608
Epoch 41/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7398 - loss: 0.5379 - val_accuracy: 0.7236 - val_loss: 0.5644
Epoch 42/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7363 - loss: 0.5378 - val_accuracy: 0.7264 - val_loss: 0.5617
Epoch 43/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7357 - loss: 0.5382 - val_accuracy: 0.7281 - val_loss: 0.5626
Epoch 44/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7488 - loss: 0.5266 - val_accuracy: 0.7277 - val_loss: 0.5607
Epoch 45/100
857/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7373 - loss: 0.5413
🔹 Model weights saved at epoch 45
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7373 - loss: 0.5413 - val_accuracy: 0.7249 - val_loss: 0.5616
Epoch 46/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7361 - loss: 0.5381 - val_accuracy: 0.7274 - val_loss: 0.5609
Epoch 47/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7393 - loss: 0.5351 - val_accuracy: 0.7284 - val_loss: 0.5639
Epoch 48/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7401 - loss: 0.5359 - val_accuracy: 0.7274 - val_loss: 0.5620
Epoch 49/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7455 - loss: 0.5313 - val_accuracy: 0.7252 - val_loss: 0.5640
Epoch 50/100
842/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7376 - loss: 0.5370
🔹 Model weights saved at epoch 50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7376 - loss: 0.5370 - val_accuracy: 0.7276 - val_loss: 0.5626
Epoch 51/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7439 - loss: 0.5303 - val_accuracy: 0.7274 - val_loss: 0.5609
Epoch 52/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7411 - loss: 0.5322 - val_accuracy: 0.7270 - val_loss: 0.5610
Epoch 53/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7406 - loss: 0.5348 - val_accuracy: 0.7273 - val_loss: 0.5616
Epoch 54/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7416 - loss: 0.5321 - val_accuracy: 0.7276 - val_loss: 0.5609
Epoch 55/100
844/858 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7406 - loss: 0.5335
🔹 Model weights saved at epoch 55
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7406 - loss: 0.5335 - val_accuracy: 0.7271 - val_loss: 0.5616
Epoch 56/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7364 - loss: 0.5382 - val_accuracy: 0.7271 - val_loss: 0.5640
Epoch 57/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7423 - loss: 0.5342 - val_accuracy: 0.7245 - val_loss: 0.5650
Epoch 58/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7420 - loss: 0.5321 - val_accuracy: 0.7261 - val_loss: 0.5628
Epoch 59/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7412 - loss: 0.5319 - val_accuracy: 0.7252 - val_loss: 0.5658
Epoch 60/100
841/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7404 - loss: 0.5336
🔹 Model weights saved at epoch 60
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7404 - loss: 0.5337 - val_accuracy: 0.7273 - val_loss: 0.5667
Epoch 61/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7396 - loss: 0.5360 - val_accuracy: 0.7264 - val_loss: 0.5663
Epoch 62/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7422 - loss: 0.5327 - val_accuracy: 0.7277 - val_loss: 0.5637
Epoch 63/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7382 - loss: 0.5362 - val_accuracy: 0.7265 - val_loss: 0.5651
Epoch 64/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7393 - loss: 0.5390 - val_accuracy: 0.7280 - val_loss: 0.5662
Epoch 65/100
846/858 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7431 - loss: 0.5325
🔹 Model weights saved at epoch 65
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7431 - loss: 0.5326 - val_accuracy: 0.7277 - val_loss: 0.5656
Epoch 66/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7416 - loss: 0.5317 - val_accuracy: 0.7257 - val_loss: 0.5649
Epoch 67/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7377 - loss: 0.5359 - val_accuracy: 0.7268 - val_loss: 0.5656
Epoch 68/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7399 - loss: 0.5326 - val_accuracy: 0.7268 - val_loss: 0.5680
Epoch 69/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7428 - loss: 0.5318 - val_accuracy: 0.7276 - val_loss: 0.5658
Epoch 70/100
857/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7407 - loss: 0.5348
🔹 Model weights saved at epoch 70
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7407 - loss: 0.5348 - val_accuracy: 0.7258 - val_loss: 0.5673
Epoch 71/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7440 - loss: 0.5293 - val_accuracy: 0.7261 - val_loss: 0.5675
Epoch 72/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7437 - loss: 0.5272 - val_accuracy: 0.7271 - val_loss: 0.5681
Epoch 73/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7404 - loss: 0.5334 - val_accuracy: 0.7265 - val_loss: 0.5692
Epoch 74/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7411 - loss: 0.5330 - val_accuracy: 0.7262 - val_loss: 0.5690
Epoch 75/100
840/858 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7384 - loss: 0.5348
🔹 Model weights saved at epoch 75
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7385 - loss: 0.5348 - val_accuracy: 0.7283 - val_loss: 0.5679
Epoch 76/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7398 - loss: 0.5330 - val_accuracy: 0.7265 - val_loss: 0.5688
Epoch 77/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7393 - loss: 0.5341 - val_accuracy: 0.7265 - val_loss: 0.5664
Epoch 78/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7395 - loss: 0.5333 - val_accuracy: 0.7264 - val_loss: 0.5684
Epoch 79/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7449 - loss: 0.5294 - val_accuracy: 0.7262 - val_loss: 0.5687
Epoch 80/100
855/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7401 - loss: 0.5329
🔹 Model weights saved at epoch 80
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7401 - loss: 0.5329 - val_accuracy: 0.7277 - val_loss: 0.5682
Epoch 81/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7438 - loss: 0.5315 - val_accuracy: 0.7261 - val_loss: 0.5692
Epoch 82/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7424 - loss: 0.5296 - val_accuracy: 0.7277 - val_loss: 0.5700
Epoch 83/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7347 - loss: 0.5379 - val_accuracy: 0.7278 - val_loss: 0.5675
Epoch 84/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7438 - loss: 0.5301 - val_accuracy: 0.7273 - val_loss: 0.5684
Epoch 85/100
854/858 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7427 - loss: 0.5289
🔹 Model weights saved at epoch 85
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7427 - loss: 0.5289 - val_accuracy: 0.7255 - val_loss: 0.5702
Epoch 86/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7383 - loss: 0.5361 - val_accuracy: 0.7283 - val_loss: 0.5712
Epoch 87/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7403 - loss: 0.5329 - val_accuracy: 0.7280 - val_loss: 0.5693
Epoch 88/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7417 - loss: 0.5333 - val_accuracy: 0.7280 - val_loss: 0.5749
Epoch 89/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7409 - loss: 0.5335 - val_accuracy: 0.7274 - val_loss: 0.5716
Epoch 90/100
848/858 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7387 - loss: 0.5351
🔹 Model weights saved at epoch 90
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7387 - loss: 0.5351 - val_accuracy: 0.7268 - val_loss: 0.5705
Epoch 91/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7413 - loss: 0.5328 - val_accuracy: 0.7276 - val_loss: 0.5710
Epoch 92/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7438 - loss: 0.5294 - val_accuracy: 0.7280 - val_loss: 0.5748
Epoch 93/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7371 - loss: 0.5359 - val_accuracy: 0.7270 - val_loss: 0.5692
Epoch 94/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7428 - loss: 0.5288 - val_accuracy: 0.7258 - val_loss: 0.5751
Epoch 95/100
840/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7350 - loss: 0.5371
🔹 Model weights saved at epoch 95
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7351 - loss: 0.5370 - val_accuracy: 0.7264 - val_loss: 0.5760
Epoch 96/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7402 - loss: 0.5325 - val_accuracy: 0.7258 - val_loss: 0.5745
Epoch 97/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7381 - loss: 0.5356 - val_accuracy: 0.7261 - val_loss: 0.5740
Epoch 98/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7367 - loss: 0.5346 - val_accuracy: 0.7273 - val_loss: 0.5720
Epoch 99/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7421 - loss: 0.5338 - val_accuracy: 0.7265 - val_loss: 0.5747
Epoch 100/100
838/858 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7404 - loss: 0.5331
🔹 Model weights saved at epoch 100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7404 - loss: 0.5331 - val_accuracy: 0.7278 - val_loss: 0.5740

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - 2ms/step - accuracy: 0.7278 - loss: 0.5740
Loss: 0.5740243196487427, Accuracy: 0.7278425693511963

In [ ]:
# Export our model to HDF5 file
import os

save_dir = "C:/Users/camei/Bootcamp-Oct2024/GitHub_HW/21_Neural_Networks_Deep_Learning/H5_files"
os.makedirs(save_dir, exist_ok=True)

# full file path for saving the model
model_filepath_keras = os.path.join(save_dir, "AlphabetSoupCharity.keras")
model_filepath_h5 = os.path.join(save_dir, "AlphabetSoupCharity.h5")

# Save the entire model
nn.save(model_filepath_keras)
nn.save(model_filepath_h5)

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
folder_path = "C:/Users/camei/Bootcamp-Oct2024/GitHub_HW/21_Neural_Networks_Deep_Learning/H5_files"
print("Files in directory:", os.listdir(folder_path))

Files in directory: ['AlphabetSoupCharity.keras', 'AlphabetSoupCharity.h5']